project:
  type: website
  output-dir: docs

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "CodesBlog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Samuelssa7
      - icon: linkedin
        href: https://www.linkedin.com/in/andrey-samuel-dev


format:
  html:
    theme:
      light: cosmo
      dark: superhero
    css: styles.css



